server:
  port: 8100

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/spring_security_summary?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    initialization-mode: always
    continue-on-error: true


#security:
#  user:
#    name: user
#    password: password

  jpa:
    hibernate:
#      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show: true

otp:
  validity:
    minutes: 10

application:
  name: spring-security-summary

