CREATE TABLE IF NOT EXISTS user_table (
id BIGINT NOT NULL PRIMARY KEY ,
name VARCHAR(40) NOT NULL,
username VARCHAR(40) NOT NULL,
password VARCHAR(60) NOT NULL,
email VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS role_table(
id BIGINT NOT NULL PRIMARY KEY,
role VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_role(
user_id BIGINT,
role_id BIGINT,
CONSTRAINT FK_user_table
FOREIGN KEY (user_id)
REFERENCES user_table (id)
ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK_role_table
FOREIGN KEY (role_id)
REFERENCES role_table (id)
ON UPDATE CASCADE ON DELETE CASCADE
);

