CREATE TABLE IF NOT EXISTS users (
id BIGINT NOT NULL PRIMARY KEY ,
name VARCHAR(40) NOT NULL,
username VARCHAR(40) NOT NULL,
password VARCHAR(60) NOT NULL,
email VARCHAR(40) NOT NULL
);

CREATE TABLE IF NOT EXISTS roles(
role VARCHAR(40) NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS user_roles(
user_id BIGINT,
role_id VARCHAR(40),
CONSTRAINT FK_user_table
FOREIGN KEY (user_id)
REFERENCES users (id)
ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK_role_table
FOREIGN KEY (role_id)
REFERENCES roles (role)
ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS one_time_password(
id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
otp VARCHAR(255),
username VARCHAR(40),
createdat DATE
);


